### ISSUE TITLE
Bug with HB 1.5.0

### ISSUE THREAD

**Issue by GevaudanBeast** [nitaybz/homebridge-foscam-security#1]
Do nothing, appear after update restart on Raspian.
All is update.
`[27/06/2022, 13:34:08] Homebridge v1.5.0 (HAP v0.10.2) (LaCaseHome) is running on port 60113.
[27/06/2022, 13:34:11] RequestError: Error: connect EHOSTUNREACH 192.168.1.62:88
    at new RequestError (/usr/local/lib/node_modules/homebridge-foscam-security/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-foscam-security/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/homebridge-foscam-security/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-foscam-security/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[27/06/2022, 13:34:11] Got SIGTERM, shutting down Homebridge...
`

**Comment by nitaybz** [comment]
This plugin is deprecated and is no longer maintained.

The underlying device, library, or API integration here has not been actively developed in many years and I have not been able to keep up with it. There are likely better-maintained alternatives for your use case in the Homebridge plugin ecosystem (search the verified plugins list).

Sorry for the long delay on any open issues, and thank you to everyone who used the plugin or contributed.
